# 上下文系统 | context system
+ 合理化智能转换
+ 条件系统的基础
+ 解决嵌套地狱
### 概述 | simple say
每一个大括号圈起来的地方,我们都可以把它看成是一个**作用域(scope)**,
每一个作用域都拥有它的**上下文(context)**.

子作用域开始时会复制一份父作用域的上下文给自己.
作用域中的上下文会随着调用具有上下文标签的函数而改变.
作用域的上下文在作用域结束后销毁,改变子作用域的上下文不会影响下面父作用域的上下文.
### 上下文标签 | context tag of function
函数的上下文标签(使用[]括起来)声明了调用函数后会改变的上下文,请看这个示例:
```
//用于导入一个add函数的函数
fun importAdd[
    //声明add函数将会加入下文中
    fun add(a : Int,b : Int)
] : Int{
    //在函数体中定义上下文函数
    fun add(a : Int,b : Int) : Int = a + b
}
//主函数
fun main{
    importAdd()
    println(add(1,2))
}
```
当然,还可以声明`val` `var` `class`,`class`依旧采用大括号表示类体,这里不再赘述
### 上下文参数 | context parameters
过度的显式传参会很累,我有个朋友就是因为多写了几个参数名快猝死进kfc抢救了.

上下文参数就是用来解决这个问题的,请看下列例子:
```
//隐式参数使用::,显式参数使用:
fun prt(text :: Str) = println(text)
//设置一个上下文参数
fun text(text : Str)[Str]{
    //隐式参数可以没有名字
    val :: Str = text
}
//主函数
fun main{
    //设置上下文参数中的Str为"ok"
    text("ok")
    //打印上下文参数中的Str
    prt()
    //或者你自己写一个上下文参数
    val :: Str = "okay"
    //此时打印"okay"
    prt()
}
```
### 调用 | invoke
允许函数把第一个参数放在**接收者**位置调用
```
fun add(a : Int,b : Int) : Int = a + b
fun main {
    1.add(2)
}
```
中缀调用将省略`.`与`()`,如`a.b(c)`的中缀调用为`a b c`.
当函数满足以下其一个条件,就可以中缀调用:
+ 函数是方法,并且调用时仅需要一个参数
+ 函数调用时仅需要两个参数
```
fun add(a : Int,b : Int) : Int = a + b
fun main {
    1 add 2
}
```
### 内联函数 | inline function
内联函数表示其函数参数必定会在原地调用.
因此,编译器得以更加智能的推导.

内联函数的函数参数必须确定的至少调用一次
也就是说不能把函数参数写在模式匹配或者非内联函数中调用

请看这个例子:
```
//计时打印一下
inline fun time(block : ()->Unit){
    val start = Time.now()
    block()
    val end = Time.now()
    println(end - start)
}
fun main() ^ Error {
    //当时间不是偶数时,为空
    val number = Time.now()
        .takeIf { it % 2 == 0 }
    //计时打印一下
    time {
        //此时知道number不为空
        number ?: Error("number is null!")
        println(number)
    }
    //由于time是内联的,因此直到time外面,number依旧是非空的
    println(number)
}
```
### 类型约束 | type constraint
类型可以附加约束,不符合约束时会警告,请看下面的例子:
```
//非零约束是整数的一个约束
constraint nonzore : Int
//为正约束是非零约束的子约束,因此为正约束隐含非零约束
constraint positive : nonzore
//断言整数非零
fun Int.isNonzore()[self : Int[nonzore]] ^ Error {
    (self == 0){
        Error("number is zero!")
    }
}
fun main() {
    val number = Time.now % 2
    number.isNonzore()
    println(1 / number)
}
```
### 异常 | exception

异常不强制要求捕获,只会警告,
如果没有声明某异常的函数抛出了某异常,
程序会立即崩溃.
异常抛出时会向上寻找异常处理器,
异常是可以恢复的,除非它的恢复值是Nothing,

请看下面的例子:
```
//声明一个异常,有返回值表示可以恢复
exception Division_By_Zero(Int) : Int
//除法
fun div(a : Int,b : Int) : Int ^ Division_By_Zero {
    when(b){
        0 -> Division_By_Zero(a)
        else -> a / b
    }
}
fun main() {
    Division_By_Zero ^ number --> {
        resume number
    }
    div(1,0) //结果是1
}